//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GifStudio.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GifStudio.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1376004565_youtube {
            get {
                object obj = ResourceManager.GetObject("1376004565_youtube", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1376197341_25_Pause {
            get {
                object obj = ResourceManager.GetObject("1376197341_25_Pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap application_cascade {
            get {
                object obj = ResourceManager.GetObject("application_cascade", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap application_tile_horizontal {
            get {
                object obj = ResourceManager.GetObject("application_tile_horizontal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap application_tile_vertical {
            get {
                object obj = ResourceManager.GetObject("application_tile_vertical", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_transition_270 {
            get {
                object obj = ResourceManager.GetObject("arrow-transition-270", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap camcorder {
            get {
                object obj = ResourceManager.GetObject("camcorder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cancel {
            get {
                object obj = ResourceManager.GetObject("cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap counter {
            get {
                object obj = ResourceManager.GetObject("counter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap disk {
            get {
                object obj = ResourceManager.GetObject("disk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap door_in {
            get {
                object obj = ResourceManager.GetObject("door_in", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download_cloud {
            get {
                object obj = ResourceManager.GetObject("download-cloud", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap films {
            get {
                object obj = ResourceManager.GetObject("films", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap help {
            get {
                object obj = ResourceManager.GetObject("help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lock_warning {
            get {
                object obj = ResourceManager.GetObject("lock-warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo_120 {
            get {
                object obj = ResourceManager.GetObject("logo_120", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo_300 {
            get {
                object obj = ResourceManager.GetObject("logo_300", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo_96 {
            get {
                object obj = ResourceManager.GetObject("logo_96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap page_white_put {
            get {
                object obj = ResourceManager.GetObject("page_white_put", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap photo {
            get {
                object obj = ResourceManager.GetObject("photo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap photo_add {
            get {
                object obj = ResourceManager.GetObject("photo_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap photo_album__minus {
            get {
                object obj = ResourceManager.GetObject("photo-album--minus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap photo_album__plus {
            get {
                object obj = ResourceManager.GetObject("photo-album--plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap photo_delete__2_ {
            get {
                object obj = ResourceManager.GetObject("photo_delete (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap photos {
            get {
                object obj = ResourceManager.GetObject("photos", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png48 {
            get {
                object obj = ResourceManager.GetObject("png48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap printer {
            get {
                object obj = ResourceManager.GetObject("printer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap report {
            get {
                object obj = ResourceManager.GetObject("report", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the number of frames to display in one second of GIF playback..
        /// </summary>
        internal static string STR_EXP_ANI_GIF_HELP_FPS {
            get {
                return ResourceManager.GetString("STR_EXP_ANI_GIF_HELP_FPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The FPS, or frames per second, is the total number of frames that will be shows to the eye in 1 second. A high FPS looks better to the naked eye, however it will cause the file size to be larger..
        /// </summary>
        internal static string STR_EXP_ANI_GIF_HELP_FPS_DETAILS {
            get {
                return ResourceManager.GetString("STR_EXP_ANI_GIF_HELP_FPS_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusting playback speed.
        /// </summary>
        internal static string STR_EXP_ANI_GIF_HELP_FPS_TOPIC {
            get {
                return ResourceManager.GetString("STR_EXP_ANI_GIF_HELP_FPS_TOPIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A higher quality setting will allow a greater number of colors to be placed in the image..
        /// </summary>
        internal static string STR_EXP_ANI_GIF_HELP_QUALITY {
            get {
                return ResourceManager.GetString("STR_EXP_ANI_GIF_HELP_QUALITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you would like to make your image appear to be more photorealistic, increase the quality, if you need the image to render faster, chose a lower quality setting, if you understand that the image may dither more..
        /// </summary>
        internal static string STR_EXP_ANI_GIF_HELP_QUALITY_DETAILS {
            get {
                return ResourceManager.GetString("STR_EXP_ANI_GIF_HELP_QUALITY_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output quality.
        /// </summary>
        internal static string STR_EXP_ANI_GIF_HELP_QUALITY_TOPIC {
            get {
                return ResourceManager.GetString("STR_EXP_ANI_GIF_HELP_QUALITY_TOPIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resizing an image will stretch the size of an image to make it bigger or smaller from its original size..
        /// </summary>
        internal static string STR_EXP_ANI_GIF_HELP_RESIZE {
            get {
                return ResourceManager.GetString("STR_EXP_ANI_GIF_HELP_RESIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When resizing, it is important to keep the width and height in proportion so the image does not appear to be distorted.\nThe large the size, the longer it will take to render the image..
        /// </summary>
        internal static string STR_EXP_ANI_GIF_HELP_RESIZE_DETAILS {
            get {
                return ResourceManager.GetString("STR_EXP_ANI_GIF_HELP_RESIZE_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resizing the output image.
        /// </summary>
        internal static string STR_EXP_ANI_GIF_HELP_RESIZE_TOPIC {
            get {
                return ResourceManager.GetString("STR_EXP_ANI_GIF_HELP_RESIZE_TOPIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trim a video so you can extract the part that you want, and not the whole thing..
        /// </summary>
        internal static string STR_EXP_ANI_GIF_HELP_TRIM {
            get {
                return ResourceManager.GetString("STR_EXP_ANI_GIF_HELP_TRIM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can select a starting time (which follows the format hours:minutes:seconds), and a length time, or how long it should last for the trim..
        /// </summary>
        internal static string STR_EXP_ANI_GIF_HELP_TRIM_DETAILS {
            get {
                return ResourceManager.GetString("STR_EXP_ANI_GIF_HELP_TRIM_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusting the video length and start time.
        /// </summary>
        internal static string STR_EXP_ANI_GIF_HELP_TRIM_TOPIC {
            get {
                return ResourceManager.GetString("STR_EXP_ANI_GIF_HELP_TRIM_TOPIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file path(s) or permissions to the files were denied..
        /// </summary>
        internal static string STR_EXP_ERROR_BAD_PATH {
            get {
                return ResourceManager.GetString("STR_EXP_ERROR_BAD_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Look at the path(s) again, and ensure they are valid. Check the filepath and make sure you have permission to access it, and that you have given this program rights to those permissions..
        /// </summary>
        internal static string STR_EXP_ERROR_BAD_PATH_DETAILS {
            get {
                return ResourceManager.GetString("STR_EXP_ERROR_BAD_PATH_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create/open file.
        /// </summary>
        internal static string STR_EXP_ERROR_BAD_PATH_TOPIC {
            get {
                return ResourceManager.GetString("STR_EXP_ERROR_BAD_PATH_TOPIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to contact server. Your internet connection may be down..
        /// </summary>
        internal static string STR_EXP_ERROR_NO_INTERNET {
            get {
                return ResourceManager.GetString("STR_EXP_ERROR_NO_INTERNET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently, the FLV downloader only supports downloading videos from http:// or https://.\nThe URL should look something like &quot;http://www.google.com/video&quot;, or &quot;https://www.google.com/video&quot;, or &quot;www.google.com/video&quot;, or &quot;http://google.com/video&quot;, etc... (No quotes though)..
        /// </summary>
        internal static string STR_EXP_FLV_DWL_ALERT_INVALIDURL {
            get {
                return ResourceManager.GetString("STR_EXP_FLV_DWL_ALERT_INVALIDURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URL.
        /// </summary>
        internal static string STR_EXP_FLV_DWL_ALERT_INVALIDURL_TOPIC {
            get {
                return ResourceManager.GetString("STR_EXP_FLV_DWL_ALERT_INVALIDURL_TOPIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No video could be found at the given url..
        /// </summary>
        internal static string STR_EXP_FLV_DWL_ALERT_NOVIDEO {
            get {
                return ResourceManager.GetString("STR_EXP_FLV_DWL_ALERT_NOVIDEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The video downloader may not be able to detect all videos. Some videos are streamed to the player, and those cannot be downloaded with this simple downloader.\nOther videos are loaded via JavaScript, and those cannot be detected with this downloader..
        /// </summary>
        internal static string STR_EXP_FLV_DWL_ALERT_NOVIDEO_DETAILS {
            get {
                return ResourceManager.GetString("STR_EXP_FLV_DWL_ALERT_NOVIDEO_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No video.
        /// </summary>
        internal static string STR_EXP_FLV_DWL_ALERT_NOVIDEO_TOPIC {
            get {
                return ResourceManager.GetString("STR_EXP_FLV_DWL_ALERT_NOVIDEO_TOPIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tbimage {
            get {
                object obj = ResourceManager.GetObject("tbimage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
